{
 "title": "Minecraft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server_name", "label": "Server Name", "query": "MonServeur MC" }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 6 },
   "targets": [
    {
     "expr": "mc_tps{job=\"minecraft\"}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 6 },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{job=\"minecraft\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type=\"allocated\", job=\"minecraft\"} - mc_jvm_memory{type=\"free\", job=\"minecraft\"}"
    }
   ]
  },
  {
   "title": "Unique Players",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 6 },
   "targets": [
    {
     "expr": "mc_players_total{job=\"minecraft\"}"
    }
   ]
  },
  {
   "title": "Tickrate (TPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "mc_tps{job=\"minecraft\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type=\"allocated\", job=\"minecraft\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "mc_jvm_memory{type=\"allocated\", job=\"minecraft\"} - mc_jvm_memory{type=\"free\", job=\"minecraft\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 14, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{job=\"minecraft\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 14, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(mc_entities_total{job=\"minecraft\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Players Online par monde",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 22, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "mc_players_online_total{job=\"minecraft\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Tick Duration (ns)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 22, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "mc_tick_duration_average{job=\"minecraft\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "mc_tick_duration_median{job=\"minecraft\"}",
     "legendFormat": "Median"
    }
   ]
  }
 ]
}